services:
  app:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: 'mariadb:10.3'
    volumes:
      - './.run/mysql:/var/lib/mysql'
    # ports:
    #   - 3306:3306 # for debugging purposes
    environment:
      - MARIADB_PORT_NUMBER=${db_port}
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=${db_user}
      - MARIADB_PASSWORD=${db_pass}
      - MARIADB_MYSQL_LOCALHOST_USER=true
    healthcheck: # delay app from starting until ready to accept connections
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"]
      interval: 5s
      timeout: 10s
      retries: 10
