services:
  app:
    build: .
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: 'mariadb:10.3'
    volumes:
      - './.run/mysql:/var/lib/mysql'
    environment:
      - MARIADB_PORT_NUMBER=${db_port}
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=${db_user}
      - MARIADB_PASSWORD=${db_pass}
    container_name: mariadb
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
