services:
  db:
    image: 'mariadb:10.3'
    # volumes:
    #   - './mysql:/var/lib/mysql'
    ports:
      - 3306:3306 # for debugging purposes
    environment:
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=monty
      - MARIADB_PASSWORD=monty
      - MARIADB_MYSQL_LOCALHOST_USER=true