services:
  tailscale:
    image: tailscale/tailscale:latest
    environment:
      - TS_HOSTNAME=hoyocodes-db
      - TS_AUTHKEY=${ts_authkey}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  db:
    image: 'mariadb:10.3'
    volumes:
      - './mysql:/var/lib/mysql'
    # ports:
    #   - 3306:3306 # for debugging purposes
    environment:
      - MARIADB_PORT_NUMBER=${db_port}
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=${db_user}
      - MARIADB_PASSWORD=${db_pass}
      - MARIADB_MYSQL_LOCALHOST_USER=true
    depends_on:
      tailscale:
        condition: service_started
    network_mode: service:tailscale
